import type { LocalizedPost } from "../types";

export const post: LocalizedPost = {
  meta: {
    slug: "itin-za-balgari-bez-poseshtenie-v-sasht",
    date: "2026-04-17",
    author: "GetUSA LLC",
    image: "/og.webp",
    readingTime: 16,
    relatedSlugs: ["ein-nomer-kakvo-e-kak-da-go-poluchite", "kak-da-registriram-llc-v-amerika-ot-bulgaria", "siddo-spogodba-bulgaria-sasht-danaci"],
  },
  translations: {
    bg: {
      title: "ITIN за българи — как да получите без посещение в САЩ (2026)",
      description: "Пълен гайд за ITIN (Individual Taxpayer Identification Number) за българи. Кога ви трябва, как се попълва Form W-7, колко време отнема и как да избегнете отказ — без да пътувате до САЩ.",
      category: "Данъци",
      tags: ["ITIN", "Form W-7", "IRS", "данъци", "документи"],
      tldr: "ITIN можете да получите изцяло от България. Процесът отнема 8-14 седмици през Certified Acceptance Agent (CAA), който замества нуждата от изпращане на оригинален паспорт. Трябва ви само ако имате конкретно данъчно задължение към САЩ — например собственост в multi-member LLC, US royalties, или дивиденти от американски акции. Ако имате само single-member LLC с EIN, ITIN обикновено НЕ ви е нужен.",
      content: [
        { id: "kakvo-e-itin", heading: "Какво е ITIN и с какво се различава от EIN", body: `<p><strong>ITIN</strong> (Individual Taxpayer Identification Number) е 9-цифрен данъчен номер, който IRS издава на физически лица без право на SSN (Social Security Number). Започва с 9 и има формат <code>9XX-XX-XXXX</code>.</p><p>Важно е да разберете разликата между трите номера:</p><ul><li><strong>SSN</strong> — само за граждани на САЩ и legal permanent residents. Вие като българин нямате право на SSN.</li><li><strong>EIN</strong> — данъчен номер на <strong>фирмата</strong>. Вашият LLC има EIN.</li><li><strong>ITIN</strong> — данъчен номер на <strong>физическото лице</strong>, когато то има данъчни задължения в САЩ но няма право на SSN.</li></ul><p>Голяма грешка която виждаме често: хора бъркат ITIN с EIN и се опитват да извадят ITIN когато всъщност им трябва само EIN. <a href="/blog/ein-nomer-kakvo-e-kak-da-go-poluchite">Прочетете гайда за EIN</a> ако не сте сигурни.</p>` },
        { id: "koga-tryabva-itin", heading: "Кога българин задължително има нужда от ITIN", body: `<p>ITIN ви трябва САМО ако сте в един от следните сценарии:</p><h3>Сценарий 1: Multi-member LLC (имате съдружник)</h3><p>Ако LLC-то ви има двама или повече собственици, IRS го третира като <strong>partnership</strong>. Всеки съдружник трябва да подаде лична данъчна декларация (<strong>Form 1040-NR</strong>) и да получи <strong>Schedule K-1</strong> от LLC-то. За тези форми ви трябва ITIN.</p><h3>Сценарий 2: US royalties и лицензионни плащания</h3><p>Ако получавате royalties от US източник (Amazon KDP книги, App Store приложения, Stock photo платформи, музикални платформи като DistroKid), платецът задържа <strong>30% withholding tax</strong> по подразбиране. С ITIN и валидна <strong>Form W-8BEN</strong>, този withholding се намалява на 5% според СИДДО (Спогодбата между България и САЩ).</p><h3>Сценарий 3: Дивиденти от US акции</h3><p>Ако имате акции в американски компании през брокер (Interactive Brokers, Charles Schwab), W-8BEN намалява withholding-а от 30% на 10% за дивиденти. Някои брокери изискват ITIN за пълна обработка.</p><h3>Сценарий 4: Продажба на US недвижим имот</h3><p>Ако някога продадете US недвижим имот, ITIN е задължителен за FIRPTA (Foreign Investment in Real Property Tax Act) декларация.</p><h3>Кога НЕ ви трябва ITIN</h3><p>За <strong>single-member LLC</strong> (само вие собственик), IRS третира LLC-то като <strong>disregarded entity</strong>. Вие подавате Form 5472 + pro-forma 1120 под EIN-а на LLC-то. <strong>ITIN не е нужен за тази форма.</strong></p><p>Това е най-честата заблуда — много българи мислят че "трябва ITIN защото имам LLC", но ако сте единствен собственик и нямате US данъчно задължение извън LLC-то, не ви трябва.</p>` },
        { id: "procesa", heading: "Процесът — стъпка по стъпка", body: `<p>Ето какво реално правите:</p><p><strong>1. Определете причината (basis)</strong> — IRS не издава ITIN "про-активно". Трябва да имате конкретна причина: подаване на данъчна декларация, W-8BEN към брокер, Schedule K-1 от partnership, и т.н. Изборът на причина определя дали трябва прикрепите данъчна декларация към заявлението.</p><p><strong>2. Попълнете Form W-7</strong> — официалната заявка за ITIN. Формата е на английски, 1 страница.</p><p><strong>3. Съберете документи</strong> — основното е валиден паспорт (най-лесният вариант). Всички детайли в следващата секция.</p><p><strong>4. Изпратете чрез Certified Acceptance Agent (CAA)</strong> — това е ключовата стъпка за българи. CAA е лицензиран от IRS да удостовери че вашият паспорт е оригинален, без да изпращате самия паспорт в САЩ. Това е причината защо НЕ ви трябва посещение в САЩ.</p><p><strong>5. Изчакайте обработка</strong> — IRS обикновено изпраща ITIN писмо на вашия адрес в България за 8-14 седмици. През пиковия сезон (февруари-април) може да се удължи до 16 седмици.</p>` },
        { id: "caa-vazhnost", heading: "Защо Certified Acceptance Agent е критичен за българи", body: `<p>Без CAA имате две опции, и двете лоши:</p><ul><li><strong>Изпращане на оригинален паспорт в САЩ</strong> — паспортът ви стои 2-3 месеца в IRS офис. Не можете да пътувате в това време. Ако се загуби по пощата, получаването на нов и повтарянето на процеса отнема още 3-4 месеца.</li><li><strong>Посещение в IRS Taxpayer Assistance Center в САЩ</strong> — трябва да пътувате, да си запишете час (често 2-3 месеца чакане), да прекарате половин ден там.</li></ul><p>С CAA нищо от това не се случва. Процесът е:</p><ol><li>Уговаряте онлайн среща (Zoom/Google Meet) с CAA</li><li>Показвате паспорта си пред камерата, той го сравнява с копията които му изпращате</li><li>Той подписва специален сертификат (Form W-7 COA) че е удостоверил паспорта</li><li>Цялото ви заявление + сертификата отива до IRS по DHL/FedEx</li></ol><p>Паспортът ви не напуска България. Времето за среща е 30-45 минути.</p><p>CAA услугата обикновено струва <strong>$200-400</strong> за първо ITIN и $100-200 за renewal. Това е допълнителен разход, но практическата полза го оправдава многократно.</p>` },
        { id: "form-w7-detaili", heading: "Form W-7 — най-честите грешки", body: `<p>W-7 изглежда проста, но има три места където българи често грешат:</p><h3>Грешка 1: Wrong reason code</h3><p>Секция "Reason you are submitting Form W-7" има 8 опции (a-h). Изборът трябва точно да отговаря на причината ви:</p><ul><li><strong>a</strong> — Nonresident alien required to obtain ITIN to claim tax treaty benefit (например W-8BEN към брокер)</li><li><strong>b</strong> — Nonresident alien filing a U.S. tax return (например Form 1040-NR)</li><li><strong>d</strong> — Dependent of U.S. citizen/resident alien (не важи за вас)</li><li><strong>h</strong> — Other — тук обикновено попада partnership income</li></ul><p>Грешен reason code = автоматичен отказ.</p><h3>Грешка 2: Foreign address formatting</h3><p>IRS иска адресът да е форматиран по US стандарт. Пример на правилен запис за български адрес:</p><pre><code>Line 1: UL. VITOSHA 15, AP. 3
Line 2: (empty)
City: SOFIA
State/Province: SOFIA
Postal code: 1000
Country: BULGARIA</code></pre><p>Кирилица в адреса = отказ. Пишете всичко с латиница.</p><h3>Грешка 3: Inconsistency с паспорта</h3><p>Име във W-7 трябва да съвпада <em>точно</em> с името в паспорта ви, включително middle names ако има. "Ivan Petrov" когато паспортът казва "Ivan Georgiev Petrov" = отказ.</p>` },
        { id: "dokumenti", heading: "Какви документи ви трябват", body: `<p>Минимумът за българин през CAA:</p><ul><li><strong>Валиден международен паспорт</strong> — задължително не e изтекъл, валиден минимум 6 месеца напред</li><li><strong>Попълнена Form W-7</strong> — мокър подпис, не дигитален</li><li><strong>Supporting document</strong> зависи от причината:<ul><li>Ако подавате 1040-NR — самата данъчна декларация</li><li>Ако правите W-8BEN за брокер — писмо от брокера (например от Interactive Brokers)</li><li>Ако сте partner в LLC — Schedule K-1 и/или operating agreement</li></ul></li></ul><p>CAA ще ви даде чеклист специфичен за вашия случай и ще се увери че всичко е наред преди да изпрати.</p>` },
        { id: "vreme-i-taksi", heading: "Време и разходи — реалистични очаквания", body: `<p><strong>IRS не взема такса</strong> за издаване на ITIN. Всички разходи са за професионалните услуги:</p><ul><li><strong>CAA услуга:</strong> $200-400 (зависи от агента)</li><li><strong>Преводи на документи:</strong> $0-100 (ако нещо не е на английски или испански)</li><li><strong>DHL/FedEx до IRS:</strong> $40-60</li><li><strong>Пощенска услуга за получаване:</strong> $20-40</li></ul><p><strong>Общо: $260-600</strong> за първо ITIN, всичко включено.</p><p><strong>Време:</strong></p><ul><li>Non-peak season (май-декември): 8-11 седмици</li><li>Peak season (януари-април): 12-16 седмици</li><li>Ако има проблеми (rejection или additional docs request): добавете още 4-6 седмици</li></ul><p>Имайте предвид че ITIN изтича ако не се използва за 3 последователни данъчни години. Renewal е малко по-бърз (6-10 седмици) и по-евтин.</p>` },
        { id: "chesti-otkazy", heading: "Чести причини за отказ (и как да ги избегнете)", body: `<p>Най-честите 5 грешки които виждаме в откази:</p><ol><li><strong>Wrong reason code</strong> (40% от отказите) — споменахме по-горе. Съвет: ако не сте сигурни, консултирайте се с CAA преди подаване.</li><li><strong>Missing supporting document</strong> (25%) — например избрахте reason (a) за treaty benefit но не приложихте писмо от brokera.</li><li><strong>Expired или soon-to-expire паспорт</strong> (15%) — IRS изисква валидност минимум 6 месеца напред от датата на обработка.</li><li><strong>Name mismatch</strong> (10%) — name в W-7 не съвпада точно с паспорта.</li><li><strong>Illegible копие на документ</strong> (10%) — при CAA това е по-рядко защото агентът проверява преди изпращане.</li></ol><p>След отказ, IRS изпраща писмо с конкретната причина. Повторното подаване е по-лесно защото вече знаете какво е липсвало.</p>` },
        { id: "alternativi", heading: "Кога да помислите за алтернативи", body: `<p>Ако имате <strong>single-member LLC</strong> и единствената ви причина да искате ITIN е "защото чух че трябва" — не ви трябва. Използвайте EIN-а на LLC-то за всичко свързано с фирмата.</p><p>Ако имате <strong>само US акции</strong> през брокер и сте investing суми под $10,000/год., понякога withholding от 30% вместо 10% може да е по-евтин от годишното поддържане на ITIN + annual filing complications. Сметнете реалния impact.</p><p>Ако имате партньор и сте в процес на <strong>преобразуване на partnership в single-member</strong> LLC, изчакайте преобразуването — ще ви спести ITIN процеса.</p><p>За случаите където ITIN е задължителен — partnership LLC, multiple income streams, active US investments — няма смислена алтернатива. Правете го веднъж, правилно, с CAA.</p>` },
        { id: "nashata-pomoshch", heading: "Как можем да помогнем", body: `<p>Ние предлагаме ITIN услугата като включваме всички стъпки:</p><ul><li>Оценка дали реално ви трябва ITIN (често първата консултация показва че не ви трябва)</li><li>Попълване на W-7 с правилен reason code</li><li>CAA удостоверяване през онлайн среща</li><li>Изпращане на документите до IRS</li><li>Проследяване на статуса</li><li>Доставка на ITIN писмото</li></ul><p>Всичко се случва от България. Свържете се за индивидуална оферта на <a href="/contact">нашата страница за контакт</a>.</p>` },
      ],
      faq: [
        { question: "Мога ли да получа ITIN без да имам LLC?", answer: "Да. ITIN е на физическото лице, не на фирмата. Можете да получите ITIN за US royalties, US investments, partnership income и други сценарии без LLC." },
        { question: "Колко време е валиден ITIN-ът?", answer: "ITIN е безсрочно валиден докато се използва редовно в данъчни декларации. Ако не се ползва 3 последователни години, изтича и трябва renewal." },
        { question: "Ако имам single-member Wyoming LLC, трябва ли ITIN?", answer: "Не, в повечето случаи. Single-member LLC е disregarded entity — подавате Form 5472 + pro-forma 1120 под EIN-а. ITIN не е нужен." },
        { question: "Мога ли да подам W-7 онлайн?", answer: "Не. IRS не приема W-7 онлайн. Трябва физически да се изпрати заявлението — с DHL/FedEx през CAA или по пощата с оригинален паспорт." },
        { question: "Колко струва цялата процедура?", answer: "Между $260 и $600 зависещи от CAA услугата и допълнителни разходи. IRS не взема такса за самия ITIN." },
        { question: "Какво се случва ако IRS откаже заявлението?", answer: "Получавате писмо с конкретна причина. Можете да подадете отново след отстраняване на проблема — няма limit на опитите, но всеки опит добавя 8-12 седмици към времето." },
        { question: "Трябва ли ITIN за да отворя Mercury или Relay сметка?", answer: "Не. Бизнес сметките в Mercury/Relay се отварят с EIN на LLC-то + вашия паспорт. ITIN не е изискван за банково отваряне." },
      ],
    },
    en: {
      title: "ITIN for Foreign Nationals — How to Get One Without Visiting the US (2026)",
      description: "Complete guide to obtaining an ITIN (Individual Taxpayer Identification Number) from outside the US. When you need one, how to fill Form W-7, processing times, and how to avoid rejection — all without traveling to the US.",
      category: "Taxes",
      tags: ["ITIN", "Form W-7", "IRS", "taxes", "documents"],
      tldr: "You can obtain an ITIN entirely from your home country. The process takes 8-14 weeks through a Certified Acceptance Agent (CAA), eliminating the need to mail your original passport. You only need an ITIN if you have a specific US tax obligation — such as partnership membership in a multi-member LLC, US royalty income, or dividends from US stocks. If you only own a single-member LLC with an EIN, you usually do NOT need an ITIN.",
      content: [
        { id: "what-is-itin", heading: "What Is an ITIN and How It Differs from EIN", body: `<p><strong>ITIN</strong> (Individual Taxpayer Identification Number) is a 9-digit tax ID the IRS issues to individuals not eligible for an SSN. It starts with 9 in the format <code>9XX-XX-XXXX</code>.</p><p>Understanding the three tax IDs is critical:</p><ul><li><strong>SSN</strong> — only for US citizens and legal permanent residents. As a foreign national, you cannot obtain one.</li><li><strong>EIN</strong> — the tax number of your <strong>company</strong>. Your LLC has an EIN.</li><li><strong>ITIN</strong> — the tax number of an <strong>individual</strong> who has US tax obligations but isn't eligible for an SSN.</li></ul><p>A common mistake: confusing ITIN with EIN and trying to get an ITIN when only an EIN is needed. <a href="/blog/ein-nomer-kakvo-e-kak-da-go-poluchite">Read our EIN guide</a> if you're uncertain.</p>` },
        { id: "when-needed", heading: "When Foreign Nationals Actually Need an ITIN", body: `<p>You need an ITIN ONLY if one of these applies:</p><h3>Scenario 1: Multi-member LLC (you have partners)</h3><p>If your LLC has two or more owners, the IRS treats it as a <strong>partnership</strong>. Each partner must file a personal tax return (<strong>Form 1040-NR</strong>) and receive a <strong>Schedule K-1</strong> from the LLC. You need an ITIN for these filings.</p><h3>Scenario 2: US royalties and licensing payments</h3><p>If you receive royalties from a US source (Amazon KDP books, App Store apps, stock photo platforms, music distribution via DistroKid), the payer withholds <strong>30% by default</strong>. With an ITIN and a valid <strong>Form W-8BEN</strong>, this withholding can be reduced based on your country's tax treaty with the US.</p><h3>Scenario 3: Dividends from US stocks</h3><p>Holding US stocks through a broker (Interactive Brokers, Charles Schwab) — the W-8BEN reduces dividend withholding from 30% to the treaty rate. Some brokers require an ITIN for full processing.</p><h3>Scenario 4: Sale of US real estate</h3><p>An ITIN is mandatory for FIRPTA (Foreign Investment in Real Property Tax Act) reporting when selling US real estate.</p><h3>When You Do NOT Need an ITIN</h3><p>For a <strong>single-member LLC</strong> (sole owner), the IRS treats it as a <strong>disregarded entity</strong>. You file Form 5472 + pro-forma 1120 under the LLC's EIN. <strong>An ITIN is not required for this filing.</strong></p><p>This is the most common misconception — many foreign owners believe they need an ITIN "because they have an LLC", but if you're the sole owner and have no US tax obligations beyond the LLC, you don't.</p>` },
        { id: "process", heading: "The Process — Step by Step", body: `<p>Here's what actually happens:</p><p><strong>1. Determine the basis</strong> — The IRS doesn't issue ITINs proactively. You need a specific reason: filing a tax return, W-8BEN for a broker, Schedule K-1 from a partnership, etc. The basis determines whether you must attach a tax return.</p><p><strong>2. Complete Form W-7</strong> — The official ITIN application. One page, English.</p><p><strong>3. Gather documents</strong> — Primarily a valid passport. Details in the next section.</p><p><strong>4. Submit through a Certified Acceptance Agent (CAA)</strong> — This is the key step for foreign applicants. A CAA is IRS-authorized to verify your passport's authenticity, eliminating the need to mail the original. This is why you don't need to visit the US.</p><p><strong>5. Wait for processing</strong> — The IRS typically mails the ITIN letter to your address in 8-14 weeks. Peak season (February-April) can extend this to 16 weeks.</p>` },
        { id: "caa-importance", heading: "Why Certified Acceptance Agent Is Critical", body: `<p>Without a CAA, you have two options, both bad:</p><ul><li><strong>Mailing your original passport to the US</strong> — Your passport sits at an IRS office for 2-3 months. You cannot travel during this time. If lost in transit, obtaining a new passport and restarting the process adds 3-4 months.</li><li><strong>Visiting an IRS Taxpayer Assistance Center in the US</strong> — You must travel, book an appointment (often 2-3 months waitlist), and spend half a day there.</li></ul><p>With a CAA, none of this happens. The process is:</p><ol><li>Schedule an online meeting (Zoom/Google Meet) with the CAA</li><li>Present your passport on camera; they compare it with the copies you've sent</li><li>They sign a special certificate (Form W-7 COA) certifying the passport's authenticity</li><li>Your entire application + certificate is sent to the IRS via DHL/FedEx</li></ol><p>Your passport never leaves your country. The meeting takes 30-45 minutes.</p><p>CAA services typically cost <strong>$200-400</strong> for first ITIN and $100-200 for renewal. An additional expense, but the practical benefit justifies it many times over.</p>` },
        { id: "w7-mistakes", heading: "Form W-7 — Most Common Mistakes", body: `<p>W-7 appears simple but has three critical error points:</p><h3>Mistake 1: Wrong reason code</h3><p>The "Reason you are submitting Form W-7" section has 8 options (a-h). Your selection must precisely match your purpose:</p><ul><li><strong>a</strong> — Nonresident alien required to obtain ITIN to claim tax treaty benefit (e.g., W-8BEN for a broker)</li><li><strong>b</strong> — Nonresident alien filing a U.S. tax return (e.g., Form 1040-NR)</li><li><strong>d</strong> — Dependent of U.S. citizen/resident alien (doesn't apply)</li><li><strong>h</strong> — Other — typically where partnership income falls</li></ul><p>Wrong reason code = automatic rejection.</p><h3>Mistake 2: Foreign address formatting</h3><p>The IRS requires US-style formatting. A correctly formatted foreign address example:</p><pre><code>Line 1: 15 MAIN STREET, APT 3
Line 2: (empty)
City: SOFIA
State/Province: SOFIA
Postal code: 1000
Country: BULGARIA</code></pre><p>Non-Latin script in address = rejection. Everything must be in Latin characters.</p><h3>Mistake 3: Passport inconsistency</h3><p>The name on W-7 must match the passport <em>exactly</em>, including middle names if present. "Ivan Petrov" when the passport reads "Ivan Georgiev Petrov" = rejection.</p>` },
        { id: "documents", heading: "Required Documents", body: `<p>Minimum documents via CAA:</p><ul><li><strong>Valid international passport</strong> — must be unexpired, valid minimum 6 months forward</li><li><strong>Completed Form W-7</strong> — wet signature, not digital</li><li><strong>Supporting document</strong> depends on basis:<ul><li>If filing 1040-NR — the tax return itself</li><li>If W-8BEN for broker — letter from broker (e.g., from Interactive Brokers)</li><li>If partner in LLC — Schedule K-1 and/or operating agreement</li></ul></li></ul><p>Your CAA will provide a case-specific checklist and verify everything before submission.</p>` },
        { id: "time-cost", heading: "Timeline and Cost — Realistic Expectations", body: `<p><strong>The IRS charges nothing</strong> for issuing an ITIN. All costs are for professional services:</p><ul><li><strong>CAA service:</strong> $200-400 (varies by agent)</li><li><strong>Document translations:</strong> $0-100 (if anything isn't in English or Spanish)</li><li><strong>DHL/FedEx to IRS:</strong> $40-60</li><li><strong>Return mail to you:</strong> $20-40</li></ul><p><strong>Total: $260-600</strong> for first ITIN, all-in.</p><p><strong>Timeline:</strong></p><ul><li>Non-peak season (May-December): 8-11 weeks</li><li>Peak season (January-April): 12-16 weeks</li><li>If issues (rejection or additional docs request): add 4-6 weeks</li></ul><p>Note: ITINs expire if not used for 3 consecutive tax years. Renewal is faster (6-10 weeks) and cheaper.</p>` },
        { id: "common-rejections", heading: "Common Rejection Reasons (and How to Avoid Them)", body: `<p>The 5 most common rejection reasons:</p><ol><li><strong>Wrong reason code</strong> (40% of rejections) — Consult a CAA before submission if unsure.</li><li><strong>Missing supporting document</strong> (25%) — e.g., selecting reason (a) for treaty benefit without attaching the broker letter.</li><li><strong>Expired or soon-to-expire passport</strong> (15%) — The IRS requires minimum 6 months validity from the processing date.</li><li><strong>Name mismatch</strong> (10%) — Name on W-7 doesn't precisely match the passport.</li><li><strong>Illegible document copy</strong> (10%) — Less common with a CAA who verifies before submission.</li></ol><p>After rejection, the IRS sends a letter with the specific reason. Resubmission is easier since you know what was missing.</p>` },
        { id: "alternatives", heading: "When to Consider Alternatives", body: `<p>If you have a <strong>single-member LLC</strong> and your only reason for wanting an ITIN is "I heard I needed one" — you don't. Use the LLC's EIN for everything related to the company.</p><p>If you only hold <strong>US stocks</strong> through a broker and invest under $10,000/year, sometimes 30% withholding vs. the treaty rate may be cheaper than annual ITIN maintenance + filing complications. Calculate the real impact.</p><p>If you have a partner and are in the process of <strong>converting a partnership to a single-member</strong> LLC, wait for the conversion — it'll save you the ITIN process.</p><p>For cases where ITIN is mandatory — partnership LLC, multiple income streams, active US investments — there's no meaningful alternative. Do it once, correctly, with a CAA.</p>` },
        { id: "our-service", heading: "How We Can Help", body: `<p>We offer ITIN service including all steps:</p><ul><li>Assessment whether you actually need an ITIN (the first consultation often reveals you don't)</li><li>Filling W-7 with the correct reason code</li><li>CAA certification via online meeting</li><li>Submission to the IRS</li><li>Status tracking</li><li>Delivery of the ITIN letter</li></ul><p>Everything happens remotely. Contact us for a custom quote on <a href="/contact">our contact page</a>.</p>` },
      ],
      faq: [
        { question: "Can I get an ITIN without having an LLC?", answer: "Yes. ITIN is for the individual, not the company. You can obtain an ITIN for US royalties, US investments, partnership income, and other scenarios without an LLC." },
        { question: "How long is an ITIN valid?", answer: "ITINs are valid indefinitely while used regularly on tax returns. If unused for 3 consecutive years, it expires and requires renewal." },
        { question: "If I have a single-member Wyoming LLC, do I need an ITIN?", answer: "Usually no. A single-member LLC is a disregarded entity — you file Form 5472 + pro-forma 1120 under the EIN. ITIN is not required." },
        { question: "Can I submit W-7 online?", answer: "No. The IRS doesn't accept W-7 online. The application must be physically mailed — via DHL/FedEx through a CAA or by mail with original passport." },
        { question: "How much does the whole procedure cost?", answer: "Between $260 and $600 depending on the CAA service and additional costs. The IRS charges nothing for the ITIN itself." },
        { question: "What happens if the IRS rejects the application?", answer: "You receive a letter with the specific reason. You can resubmit after fixing the issue — no limit on attempts, but each adds 8-12 weeks to the timeline." },
        { question: "Do I need an ITIN to open Mercury or Relay account?", answer: "No. Business accounts at Mercury/Relay open with the LLC's EIN + your passport. ITIN is not required for banking." },
      ],
    },
  },
};
