import type { LocalizedPost } from "../types";

export const post: LocalizedPost = {
  meta: {
    slug: "siddo-spogodba-bulgaria-sasht-danaci",
    date: "2026-04-14",
    author: "GetUSA LLC",
    image: "/og.webp",
    readingTime: 20,
    relatedSlugs: ["kak-da-registriram-llc-v-amerika-ot-bulgaria", "ein-nomer-kakvo-e-kak-da-go-poluchite", "stripe-ot-bulgaria-s-amerikansko-llc"],
  },
  translations: {
    bg: {
      title: "СИДДО спогодба България-САЩ — Как да не плащате данъци два пъти (2026)",
      description: "Пълен гайд за СИДДО спогодбата. Как да избегнете двойно облагане, какви декларации трябва да подавате и кога дължите данъци.",
      category: "Данъци",
      tags: ["СИДДО", "данъци", "САЩ", "България", "LLC", "IRS"],
      tldr: "СИДДО предотвратява двойно облагане. Без офис/служители в САЩ, доходите от LLC се облагат само в България. Но задължително подавайте годишна декларация (Form 5472 + 1120) — глоба за неподаване: $25,000.",
      content: [
        { id: "kakvo-e-siddo", heading: "Какво е СИДДО и защо е критично важно", body: `<p>СИДДО е двустранно споразумение между България и САЩ, в сила от 15 декември 2008 г.</p><p><strong>Без СИДДО:</strong> И двете държави облагат доходите ви → плащате данъци два пъти.</p><p><strong>Със СИДДО:</strong> Определя коя държава облага какъв доход. За повечето българи с LLC → облагане <strong>само в България</strong>.</p><p>Ключови членове:</p><ul><li><strong>Член 7:</strong> Печалби от стопанска дейност — облагат се само в държавата на предприятието, освен ако има PE</li><li><strong>Член 5:</strong> Определя "място на стопанска дейност" (PE) — офис, клон, склад</li><li><strong>Член 14:</strong> Доходи от свободни професии</li></ul>` },
        { id: "koga-ne-dulzite", heading: "Кога НЕ дължите данъци в САЩ", body: `<p>Не дължите федерален данък ако:</p><p><strong>1. Нямате PE в САЩ:</strong> нито офис, нито служители, нито склад. Registered Agent НЕ е PE. Mercury сметка НЕ е PE.</p><p><strong>2. LLC е single-member disregarded entity:</strong> Доходите pass through към собственика и се облагат в България.</p><p><strong>3. Нямате US-source income:</strong> Работата се извършва от България → foreign-source.</p><p><strong>Накратко:</strong> Живеете в България + работите от България + без присъствие в САЩ = данъци <strong>само в България</strong>.</p>` },
        { id: "koga-dulzite", heading: "Кога ДЪЛЖИТЕ данъци в САЩ", body: `<p><strong>1. PE в САЩ:</strong> Офис, склад, служители → облагане на свързаните доходи.</p><p><strong>2. Effectively Connected Income:</strong> Консултантски услуги, извършвани физически в САЩ.</p><p><strong>3. FDAP Income:</strong> Дивиденти, лихви, наеми от US имоти — 30% withholding (намален по СИДДО).</p><p><strong>4. US партньор в LLC:</strong> Усложнява данъчната ситуация.</p><p><strong>5. Избрали сте C-Corp облагане:</strong> 21% корпоративен данък.</p><p>Повечето от тези сценарии не са типични за онлайн бизнес. При съмнение — <a href="/contact">консултирайте CPA</a>.</p>` },
        { id: "zadulzitelni-deklaracii", heading: "Задължителни данъчни декларации", body: `<p><strong>Дори без данъци, подавайте декларации!</strong></p><p><strong>Single-Member LLC:</strong> Form 5472 + Form 1120 до 15 април. Глоба: <strong>$25,000</strong>.</p><p><strong>Multi-Member LLC:</strong> Form 1065 + Schedule K-1 до 15 март.</p><p><strong>Щатски:</strong> Annual Report (Wyoming: $60). Franchise Tax (Delaware: $300).</p><p><strong>Календар:</strong></p><ul><li>15 март: Form 1065 (multi-member)</li><li>15 април: Form 5472 + 1120 (single-member)</li><li>1 юни: Delaware Franchise Tax</li><li>Варира: Wyoming Annual Report</li></ul>` },
        { id: "danaci-v-bulgaria", heading: "Облагане на LLC доходите в България", body: `<p><strong>Физически лица:</strong> 10% плосък данък + осигуровки. Годишна декларация до 30 април.</p><p><strong>Чрез ЕООД:</strong> 10% корпоративен + 5% данък дивидент при изтегляне.</p><p><strong>За СИДДО:</strong> Може да ви трябва удостоверение за данъчна резиденция от НАП и W-8BEN-E форма.</p><p>Работете с <a href="/contact">CPA, запознат със СИДДО</a>, за правилна подготовка на документите.</p>` },
        { id: "prakticheski-primeri", heading: "Практически примери", body: `<p><strong>Фрийлансър, $50,000/год.:</strong> US данъци: $0. BG данъци: ~$5,000 + осигуровки. US декларация: задължителна.</p><p><strong>SaaS, $200,000/год.:</strong> US данъци: $0. BG данъци: 10% върху печалбата. Wyoming: $60/год.</p><p><strong>Amazon FBA с US склад:</strong> Инвентарът може да създаде PE! Професионална консултация задължителна.</p><p><strong>Двама собственици (BG + US):</strong> Сложна ситуация — US партньорът дължи US данъци. Form 1065 задължителна.</p>` },
        { id: "greshki-pri-danacite", heading: "Най-опасните грешки при данъците", body: `<p><strong>1. Неподаване на Form 5472</strong> — $25,000 глоба, автоматична.</p><p><strong>2. Непознаване на СИДДО</strong> — банки могат да удържат 30% данък.</p><p><strong>3. Смесване на лични и бизнес средства</strong> — губите защитата на LLC.</p><p><strong>4. Грешна класификация</strong> — не подавайте Form 8832 без да знаете последствията.</p><p><strong>5. Игнориране на щатски изисквания</strong> — Annual Report, Franchise Tax.</p><p><strong>6. Nexus за sales tax</strong> — Amazon FBA може да създаде задължения.</p><p>За да избегнете тези капани: <a href="/contact">лицензиран CPA</a>.</p>` },
      ],
      faq: [
        { question: "Мога ли да избегна всички данъци?", answer: "Не. Дължите данъци в България (10%). СИДДО предотвратява двойно облагане, не освобождава от данъци." },
        { question: "Какво е Form 5472?", answer: "Информационна декларация за транзакции между LLC и чуждестранния собственик. Задължителна. Глоба $25,000." },
        { question: "Трябва ли ми US счетоводител?", answer: "Силно препоръчително. CPA ще подготви декларациите и ще ви спести хиляди от потенциални глоби." },
        { question: "СИДДО автоматична ли е?", answer: "Не винаги. Може да трябва W-8BEN-E и удостоверение за резиденция от НАП." },
        { question: "Какво е permanent establishment?", answer: "Място на стопанска дейност — офис, клон, склад в САЩ. Без PE = без US данъци." },
      ],
    },
    en: {
      title: "US Tax Treaty Guide for Foreign LLC Owners — How to Avoid Double Taxation (2026)",
      description: "Complete guide to US tax treaties for foreign LLC owners. How to avoid double taxation, what returns you must file and when you owe tax.",
      category: "Taxes",
      tags: ["tax treaty", "taxes", "USA", "LLC", "IRS"],
      tldr: "Tax treaties prevent double taxation. Without an office or employees in the US, LLC income is taxed only in your home country. But the annual return is mandatory (Form 5472 + 1120) — penalty for non-filing: $25,000.",
      content: [
        { id: "kakvo-e-siddo", heading: "What a tax treaty is and why it matters", body: `<p>A tax treaty is a bilateral agreement between two countries that determines how income is taxed when it crosses borders.</p><p><strong>Without a treaty:</strong> Both countries tax your income → you pay tax twice.</p><p><strong>With a treaty:</strong> It defines which country taxes which income. For most foreign founders with an LLC → taxation <strong>only at home</strong>.</p><p>Key articles in most US treaties:</p><ul><li><strong>Article 7:</strong> Business profits — taxed only in the country of the enterprise unless there is a PE</li><li><strong>Article 5:</strong> Defines "Permanent Establishment" (PE) — office, branch, warehouse</li><li><strong>Article 14:</strong> Income from independent personal services</li></ul>` },
        { id: "koga-ne-dulzite", heading: "When you DO NOT owe US taxes", body: `<p>You don't owe federal tax if:</p><p><strong>1. You have no PE in the US:</strong> no office, no employees, no warehouse. A Registered Agent is NOT a PE. A Mercury account is NOT a PE.</p><p><strong>2. The LLC is a single-member disregarded entity:</strong> Income passes through to the owner and is taxed at home.</p><p><strong>3. You have no US-source income:</strong> Work is performed from your home country → foreign-source.</p><p><strong>In short:</strong> You live abroad + work from abroad + no US presence = taxes <strong>only at home</strong>.</p>` },
        { id: "koga-dulzite", heading: "When you DO owe US taxes", body: `<p><strong>1. PE in the US:</strong> Office, warehouse, employees → taxation of related income.</p><p><strong>2. Effectively Connected Income:</strong> Consulting services performed physically in the US.</p><p><strong>3. FDAP Income:</strong> Dividends, interest, rent from US property — 30% withholding (reduced under the treaty).</p><p><strong>4. US partner in the LLC:</strong> Complicates the tax situation.</p><p><strong>5. You elected C-Corp taxation:</strong> 21% corporate tax.</p><p>Most of these scenarios are not typical for an online business. If in doubt — <a href="/contact">consult a CPA</a>.</p>` },
        { id: "zadulzitelni-deklaracii", heading: "Mandatory tax filings", body: `<p><strong>Even with no taxes due, file the returns!</strong></p><p><strong>Single-Member LLC:</strong> Form 5472 + Form 1120 by April 15. Penalty: <strong>$25,000</strong>.</p><p><strong>Multi-Member LLC:</strong> Form 1065 + Schedule K-1 by March 15.</p><p><strong>State:</strong> Annual Report (Wyoming: $60). Franchise Tax (Delaware: $300).</p><p><strong>Calendar:</strong></p><ul><li>March 15: Form 1065 (multi-member)</li><li>April 15: Form 5472 + 1120 (single-member)</li><li>June 1: Delaware Franchise Tax</li><li>Varies: Wyoming Annual Report</li></ul>` },
        { id: "danaci-v-bulgaria", heading: "Taxation of LLC income at home", body: `<p><strong>Individuals:</strong> Apply your country's personal income tax rate plus social contributions. Annual return per local deadline.</p><p><strong>Through a local LTD:</strong> Local corporate tax + dividend tax on withdrawal.</p><p><strong>For the treaty:</strong> You may need a tax residency certificate from your local tax authority and a W-8BEN-E form.</p><p>Work with a <a href="/contact">CPA familiar with US tax treaties</a> for proper document preparation.</p>` },
        { id: "prakticheski-primeri", heading: "Practical examples", body: `<p><strong>Freelancer, $50,000/yr:</strong> US tax: $0. Local tax: at your local rate + social contributions. US filing: mandatory.</p><p><strong>SaaS, $200,000/yr:</strong> US tax: $0. Local tax on profit. Wyoming: $60/yr.</p><p><strong>Amazon FBA with US warehouse:</strong> Inventory may create PE! Professional consultation mandatory.</p><p><strong>Two owners (foreign + US):</strong> Complex situation — the US partner owes US taxes. Form 1065 mandatory.</p>` },
        { id: "greshki-pri-danacite", heading: "The most dangerous tax mistakes", body: `<p><strong>1. Not filing Form 5472</strong> — $25,000 penalty, automatic.</p><p><strong>2. Not knowing the treaty</strong> — banks can withhold 30% tax.</p><p><strong>3. Mixing personal and business funds</strong> — you lose the LLC protection.</p><p><strong>4. Wrong classification</strong> — don't file Form 8832 without knowing the consequences.</p><p><strong>5. Ignoring state requirements</strong> — Annual Report, Franchise Tax.</p><p><strong>6. Sales tax nexus</strong> — Amazon FBA can create obligations.</p><p>To avoid these traps: <a href="/contact">licensed CPA</a>.</p>` },
      ],
      faq: [
        { question: "Can I avoid all taxes?", answer: "No. You owe taxes at home. The treaty prevents double taxation, it does not exempt you from tax." },
        { question: "What is Form 5472?", answer: "An information return for transactions between the LLC and the foreign owner. Mandatory. $25,000 penalty." },
        { question: "Do I need a US accountant?", answer: "Strongly recommended. A CPA will prepare the returns and save you thousands in potential penalties." },
        { question: "Is the treaty automatic?", answer: "Not always. You may need a W-8BEN-E and a residency certificate from your local tax authority." },
        { question: "What is a permanent establishment?", answer: "A place of business — office, branch, warehouse in the US. No PE = no US tax." },
      ],
    },
  },
};
