import type { LocalizedPost } from "../types";

export const post: LocalizedPost = {
  meta: {
    slug: "stripe-ot-bulgaria-s-amerikansko-llc",
    date: "2026-04-14",
    author: "GetUSA LLC",
    image: "/og.webp",
    readingTime: 16,
    relatedSlugs: ["kak-da-registriram-llc-v-amerika-ot-bulgaria", "wyoming-vs-delaware-koj-shtat-za-bulgari", "ein-nomer-kakvo-e-kak-da-go-poluchite"],
  },
  translations: {
    bg: {
      title: "Stripe от България — Как да приемате плащания с американско LLC (2026)",
      description: "Stripe не работи с български фирми. Научете как да активирате Stripe чрез американско LLC и да приемате картови плащания от целия свят.",
      category: "Плащания",
      tags: ["Stripe", "плащания", "LLC", "България", "Mercury", "e-commerce"],
      tldr: "За Stripe от България ви трябва: американско LLC, EIN и Mercury банкова сметка. Активирането отнема 1-3 дни. Stripe поддържа 135+ валути и е ключов за SaaS, e-commerce и фрийланс.",
      content: [
        { id: "zashto-stripe", heading: "Защо Stripe е критично важен за българските предприемачи", body: `<p>Stripe е най-големият платежен процесор в света — обработва плащания за Shopify, Amazon, Google и милиони малки бизнеси.</p><ul><li><strong>Глобално покритие:</strong> 195+ държави, 135+ валути</li><li><strong>Ниски такси:</strong> 2.9% + $0.30 за US карти</li><li><strong>Абонаменти:</strong> Вграден Stripe Billing за SaaS</li><li><strong>Лесна интеграция:</strong> Shopify, WordPress, WooCommerce, custom</li></ul><p><strong>Проблемът:</strong> Stripe не поддържа български фирми. България не е в списъка на поддържаните държави. Единственият начин е чрез <a href="/blog/kak-da-registriram-llc-v-amerika-ot-bulgaria">американско LLC</a>.</p>` },
        { id: "kakvo-vi-trqbva", heading: "Какво ви трябва — чеклист", body: `<p><strong>1. Американско LLC</strong> — регистрирано в <a href="/blog/wyoming-vs-delaware-koj-shtat-za-bulgari">Wyoming</a> или друг щат.</p><p><strong>2. <a href="/blog/ein-nomer-kakvo-e-kak-da-go-poluchite">EIN номер</a></strong> — данъчен номер от IRS.</p><p><strong>3. Mercury банкова сметка</strong> — за получаване на изплащания от Stripe.</p><p><strong>Допълнително:</strong> Паспорт, бизнес адрес в САЩ, описание на бизнеса, активен уебсайт.</p>` },
        { id: "stypka-po-stypka-stripe", heading: "Стъпка по стъпка: Активиране на Stripe", body: `<p><strong>1.</strong> Регистрирайте се на stripe.com</p><p><strong>2.</strong> Попълнете бизнес информация: LLC тип, име, EIN, адрес, индустрия, уебсайт</p><p><strong>3.</strong> Лична информация: име, дата на раждане, паспортен номер (ако нямате SSN)</p><p><strong>4.</strong> Свържете Mercury: routing number + account number. Stripe прави тестов депозит.</p><p><strong>5.</strong> Верификация: 1-3 работни дни. Може да поискат Articles of Organization.</p><p><strong>6.</strong> Интеграция: Получавате API ключове за Stripe Checkout, Payment Links или Elements.</p>` },
        { id: "stripe-vs-alternativite", heading: "Stripe vs PayPal vs Square vs Wise", body: `<p><strong>Stripe:</strong> 2.9% + $0.30. Най-добра интеграция, абонаменти, invoicing. Идеален за SaaS, e-commerce.</p><p><strong>PayPal Business:</strong> 3.49% + $0.49. По-скъп, но разпознаваем. Чести замразявания на акаунти.</p><p><strong>Square:</strong> 2.9% + $0.30. Добър за POS, но по-ограничен онлайн.</p><p><strong>Wise Business:</strong> Не е платежен процесор — за банкови преводи с ниски такси.</p><p><strong>Препоръка:</strong> Stripe основен + PayPal допълнителен + Wise за преводи.</p>` },
        { id: "chesti-problemi", heading: "Чести проблеми при Stripe и как да ги избегнете", body: `<p><strong>1. "Бизнесът не може да бъде верифициран"</strong> — изчакайте 1-2 седмици след LLC регистрацията.</p><p><strong>2. Допълнителни документи</strong> — имайте Articles of Organization и Operating Agreement в PDF.</p><p><strong>3. Задържани средства</strong> — нормално за нови акаунти (2-3% за 90-120 дни).</p><p><strong>4. High-risk категория</strong> — проверете Stripe Restricted Businesses списъка.</p><p><strong>5. Несъответствие LLC/сайт</strong> — уверете се, че сайтът описва дейността на LLC-то.</p>` },
        { id: "stripe-za-saas", heading: "Stripe за SaaS бизнеси от България", body: `<p><strong>Stripe Billing:</strong> Абонаменти, пробни периоди, ъпгрейди. Автоматично фактуриране.</p><p><strong>Stripe Checkout:</strong> Hosted платежна страница, 10-15% по-добра конверсия. Apple Pay, Google Pay.</p><p><strong>Customer Portal:</strong> Клиентите управляват абонаментите си без да пишете код.</p><p><strong>Stripe Tax:</strong> Автоматичен sales tax и ДДС.</p><p>За SaaS от България: <a href="/blog/kak-da-registriram-llc-v-amerika-ot-bulgaria">LLC в Wyoming</a> + <a href="/blog/ein-nomer-kakvo-e-kak-da-go-poluchite">EIN</a> + Mercury + Stripe. 4-6 седмици. <a href="/contact">Можем да помогнем</a>.</p>` },
        { id: "stripe-za-ecommerce", heading: "Stripe за e-commerce и Shopify", body: `<p><strong>Shopify Payments</strong> е built on Stripe. С LLC активирате Shopify Payments и избягвате 2% допълнителна такса.</p><p><strong>WooCommerce + Stripe:</strong> Безплатен плъгин, лесна настройка.</p><p><strong>Amazon FBA:</strong> LLC позволява Professional Seller акаунт. Плащанията постъпват в Mercury.</p><p><strong>Дигитални продукти:</strong> Stripe + Gumroad или Lemon Squeezy за прости продажби.</p>` },
        { id: "izplashtane-v-bulgaria", heading: "Как да изтеглите парите в България", body: `<p><strong>Клиент → Stripe → Mercury → Wise → Българска банка</strong></p><p><strong>Stripe → Mercury:</strong> Автоматични изплащания, T+2 дни.</p><p><strong>Mercury → Wise:</strong> ACH трансфер (безплатно). Wise има най-добър курс USD → BGN.</p><p><strong>Wise → Българска банка:</strong> 0.4-0.6% такса, директно в левове.</p><p><strong>Важно:</strong> Всички средства подлежат на деклариране по <a href="/blog/siddo-spogodba-bulgaria-sasht-danaci">СИДДО</a>. Консултирайте <a href="/contact">CPA</a> за данъчна стратегия.</p>` },
      ],
      faq: [
        { question: "Може ли Stripe да ми откаже?", answer: "Да, за restricted категории. Уверете се, че имате активен сайт и бизнесът не е в забранения списък." },
        { question: "Колко е първото изплащане?", answer: "7 дни за нови акаунти, после 2-дневен цикъл. Instant Payouts: +1% такса." },
        { question: "Мога ли без уебсайт?", answer: "Да, с Payment Links. Но сайт помага при верификация." },
        { question: "Месечни такси?", answer: "Нула. Само процент от транзакции: 2.9% + $0.30 (US), 3.9% + $0.30 (международни)." },
      ],
    },
    en: {
      title: "Stripe from Abroad — How to Accept Payments with a US LLC (2026)",
      description: "Stripe doesn't work in many countries. Learn how to activate Stripe through a US LLC and accept card payments worldwide.",
      category: "Payments",
      tags: ["Stripe", "payments", "LLC", "Mercury", "e-commerce"],
      tldr: "For Stripe from abroad you need: a US LLC, an EIN and a Mercury bank account. Activation takes 1-3 days. Stripe supports 135+ currencies and is essential for SaaS, e-commerce and freelance.",
      content: [
        { id: "zashto-stripe", heading: "Why Stripe is critical for foreign founders", body: `<p>Stripe is the largest payment processor in the world — it handles payments for Shopify, Amazon, Google and millions of small businesses.</p><ul><li><strong>Global coverage:</strong> 195+ countries, 135+ currencies</li><li><strong>Low fees:</strong> 2.9% + $0.30 for US cards</li><li><strong>Subscriptions:</strong> Built-in Stripe Billing for SaaS</li><li><strong>Easy integration:</strong> Shopify, WordPress, WooCommerce, custom</li></ul><p><strong>The problem:</strong> Stripe doesn't support many countries. The only way is through a <a href="/blog/kak-da-registriram-llc-v-amerika-ot-bulgaria">US LLC</a>.</p>` },
        { id: "kakvo-vi-trqbva", heading: "What you need — checklist", body: `<p><strong>1. US LLC</strong> — registered in <a href="/blog/wyoming-vs-delaware-koj-shtat-za-bulgari">Wyoming</a> or another state.</p><p><strong>2. <a href="/blog/ein-nomer-kakvo-e-kak-da-go-poluchite">EIN</a></strong> — tax ID from the IRS.</p><p><strong>3. Mercury bank account</strong> — to receive Stripe payouts.</p><p><strong>Additional:</strong> Passport, US business address, business description, active website.</p>` },
        { id: "stypka-po-stypka-stripe", heading: "Step by step: Stripe activation", body: `<p><strong>1.</strong> Sign up at stripe.com</p><p><strong>2.</strong> Fill in business information: LLC type, name, EIN, address, industry, website</p><p><strong>3.</strong> Personal information: name, date of birth, passport number (if you don't have an SSN)</p><p><strong>4.</strong> Connect Mercury: routing number + account number. Stripe makes a test deposit.</p><p><strong>5.</strong> Verification: 1-3 business days. They may ask for Articles of Organization.</p><p><strong>6.</strong> Integration: You receive API keys for Stripe Checkout, Payment Links or Elements.</p>` },
        { id: "stripe-vs-alternativite", heading: "Stripe vs PayPal vs Square vs Wise", body: `<p><strong>Stripe:</strong> 2.9% + $0.30. Best integration, subscriptions, invoicing. Ideal for SaaS, e-commerce.</p><p><strong>PayPal Business:</strong> 3.49% + $0.49. More expensive but recognizable. Frequent account freezes.</p><p><strong>Square:</strong> 2.9% + $0.30. Good for POS but more limited online.</p><p><strong>Wise Business:</strong> Not a payment processor — for low-fee bank transfers.</p><p><strong>Recommendation:</strong> Stripe primary + PayPal secondary + Wise for transfers.</p>` },
        { id: "chesti-problemi", heading: "Common Stripe problems and how to avoid them", body: `<p><strong>1. "Business cannot be verified"</strong> — wait 1-2 weeks after LLC registration.</p><p><strong>2. Additional documents</strong> — keep Articles of Organization and Operating Agreement as PDFs.</p><p><strong>3. Held funds</strong> — normal for new accounts (2-3% for 90-120 days).</p><p><strong>4. High-risk category</strong> — check the Stripe Restricted Businesses list.</p><p><strong>5. LLC/site mismatch</strong> — make sure the site describes the LLC's activity.</p>` },
        { id: "stripe-za-saas", heading: "Stripe for SaaS businesses", body: `<p><strong>Stripe Billing:</strong> Subscriptions, trial periods, upgrades. Automatic invoicing.</p><p><strong>Stripe Checkout:</strong> Hosted payment page, 10-15% better conversion. Apple Pay, Google Pay.</p><p><strong>Customer Portal:</strong> Customers manage their subscriptions without you writing code.</p><p><strong>Stripe Tax:</strong> Automatic sales tax and VAT.</p><p>For SaaS from abroad: <a href="/blog/kak-da-registriram-llc-v-amerika-ot-bulgaria">LLC in Wyoming</a> + <a href="/blog/ein-nomer-kakvo-e-kak-da-go-poluchite">EIN</a> + Mercury + Stripe. 4-6 weeks. <a href="/contact">We can help</a>.</p>` },
        { id: "stripe-za-ecommerce", heading: "Stripe for e-commerce and Shopify", body: `<p><strong>Shopify Payments</strong> is built on Stripe. With an LLC you activate Shopify Payments and avoid the 2% additional fee.</p><p><strong>WooCommerce + Stripe:</strong> Free plugin, easy setup.</p><p><strong>Amazon FBA:</strong> LLC enables a Professional Seller account. Payments go into Mercury.</p><p><strong>Digital products:</strong> Stripe + Gumroad or Lemon Squeezy for simple sales.</p>` },
        { id: "izplashtane-v-bulgaria", heading: "How to withdraw the money home", body: `<p><strong>Customer → Stripe → Mercury → Wise → Local bank</strong></p><p><strong>Stripe → Mercury:</strong> Automatic payouts, T+2 days.</p><p><strong>Mercury → Wise:</strong> ACH transfer (free). Wise has the best USD exchange rate.</p><p><strong>Wise → Local bank:</strong> 0.4-0.6% fee, direct in local currency.</p><p><strong>Important:</strong> All funds are subject to declaration under the <a href="/blog/siddo-spogodba-bulgaria-sasht-danaci">tax treaty</a>. Consult a <a href="/contact">CPA</a> for tax strategy.</p>` },
      ],
      faq: [
        { question: "Can Stripe reject me?", answer: "Yes, for restricted categories. Make sure you have an active site and the business isn't on the prohibited list." },
        { question: "When is the first payout?", answer: "7 days for new accounts, then a 2-day cycle. Instant Payouts: +1% fee." },
        { question: "Can I do without a website?", answer: "Yes, with Payment Links. But a site helps verification." },
        { question: "Monthly fees?", answer: "Zero. Only a percentage of transactions: 2.9% + $0.30 (US), 3.9% + $0.30 (international)." },
      ],
    },
  },
};
